### ISSUE TITLE
Unable to use it with standalone RST files

### ISSUE THREAD

**Issue by ssbarnea** [searKing/preview-vscode#37]
Some projects are using RST files without having sphinx documentation in them, so they do not have any `conf.py`. On all of these the extension is choking with something like:
```
Error
Command failed: /Users/ssbarnea/.pyenv/shims/python -m sphinx -b html . "~/.cache/rst"

Sphinx error:
master file /Users/ssbarnea/c/opendev/ansible-role-collect-logs/docs/source/index.rst not found

Error: Command failed: /Users/ssbarnea/.pyenv/shims/python -m sphinx -b html . "~/.cache/rst"

Sphinx error:
master file /Users/ssbarnea/c/opendev/ansible-role-collect-logs/docs/source/index.rst not found

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)


Sphinx error:
master file /Users/ssbarnea/c/opendev/ansible-role-collect-logs/docs/source/index.rst not found

```

That is a simple repository with a `README.rst` in its root.

**Comment by searKing** [comment]
Hi, Preview[2.3.2] is updated to use the Markdown API, Now sphinx is removed.
